### ISSUE TITLE
Deleting header

### ISSUE THREAD

**Issue by SibSibSibbis** [tidythemes/blankslate#13]
Hi,

I'd like to delete the entire header including the search field and title of the page.

How can I do so?

Thanks.

**Comment by leecollings** [comment]
By deleting the code associated with the search field and title of the page?

This theme is for you to take and to use as you wish.

**Comment by SibSibSibbis** [comment]
Thank you @leecollings.

Which code lines do I have to delete? Sorry for asking, I'm quite new to this topic.

**Comment by leecollings** [comment]
You're supposed to take this theme and change it how you want to code your site. If you're unsure where to look, then you shouldn't be using this theme.

**Comment by arealperson012** [comment]
> You're supposed to take this theme and change it how you want to code your site. If you're unsure where to look, then you shouldn't be using this theme.

That's kind of silly.  I want to use this theme and remove the header so that I can use Elementor or something like that to make a basic homepage.  Why can't you just say which lines to delete so that your blank slate is more useful to people who don't need to learn HTML because we're way beyond that phase of the internet?

**Comment by devski-dev** [comment]
Hi @arealperson012, I just came along as I also started using the theme and saw your comment. As I understand the purpose of the theme from the descriptions I found, it is meant to be a **boilerplate**/**starting point** to develop y more suiting and sophisticated **theme** FROM it. So we would want to take it and start to adjust templates, add CSS, functionality etc. to our own needs. This is what starter themes are meant for in general. So my suggestion would be, that if you have no insights on HTML whatsoever and are just for looking for sth. you can click, install and customize, you should not use this theme. It is, in my opinion, more suited for peolple with a little developing experience (who are not "beyond that phase of the internet" :-)) 

And if I may add this personal note: I think you could try to be less offensive. WordPress & this theme are completely free for you. People put their experience, craft and time in it for us to use it without asking any compensation. I think this is really great and am really thankful I can build my career upon open source software.

**Comment by devski-dev** [comment]
@SibSibSibbis As I write before I am not sure this basic starter theme is what is best for you and I really have no idea what the side effects may be because I am not very experienced with WordPress and also just installed this boilerplate theme, but assuming you want -as you said- delete the _entire header_ and _search field_:

I had a look in the browser: The element that holds both is the `

> <header id="header"> 

`element. 

If you search for it in the project's theme folder  you'll find it in the _header.php_ file. Location of the file: _yourwpinstallfolder/wp-content/themes/blankslate/header.php_

You could delete the whole <header> element, but it also contains the navigation menu. So I would comment out the parts (.branding and .search) you do not want to see. That way they are not rendered but remain in the file. This 

`<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
<meta name="viewport" content="width=device-width" />
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<div id="wrapper" class="hfeed">
<header id="header">
    
    <nav id="menu">
        
        
        <?php wp_nav_menu( array( 'theme_location' => 'main-menu' ) ); ?>
    </nav>
</header>
<div id="container">`

**Comment by devski-dev** [comment]
Hi @SibSibSibbis As I wrote before I am not sure this basic starter theme is what is best for you and I have no idea what the side effects may be because I am not very experienced with WordPress and also just installed this boilerplate theme, but assuming you want -as you said- delete the title and search field:

I had a look in the browser: The element that holds both is the `<header id="header">` element.

If you search for it in the project's theme folder you'll find it in the _header.php_ file. Location of the file is: _yourWPinstallfolder/wp-content/themes/blankslate/header.php_

You could delete the whole header element, but it also contains the navigation menu. So I would _comment out_ the parts (_.branding_ and _.search_) you do not want to see. That way they are not rendered but remain in the file. This would be the edited header file then:

```
<header id="header">
    <!--<div id="branding">
        <div id="site-title">
            <?php if ( is_front_page() || is_home() || is_front_page() && is_home() ) { echo '<h1>'; } ?>
            <a href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_html( get_bloginfo( 'name' ) ); ?>" rel="home"><?php echo esc_html( get_bloginfo( 'name' ) ); ?></a>
            <?php if ( is_front_page() || is_home() || is_front_page() && is_home() ) { echo '</h1>'; } ?>
        </div>
        <div id="site-description"><?php bloginfo( 'description' ); ?></div>
    </div>-->
    <nav id="menu">
        <!--<div id="search"><?php get_search_form(); ?></div>-->
        <!-- This needs to remain in the code in order to render the menu! -->
        <?php wp_nav_menu( array( 'theme_location' => 'main-menu' ) ); ?>
    </nav>
</header>
```

**Comment by leecollings** [comment]
You cannot simply comment out the HTML markup as all the PHP between the comments will be performed (unless that’s commented out separately). You should delete those entire blocks completely.

**Comment by devski-dev** [comment]
@leecollings Thanks for pointing that out, I just forgot to add the php comments in my post.

**Comment by bhadaway** [comment]
Hello,

Original creator of BlankSlate here. I'm sorry for the long hiatus, but I have been given permission to once again manage the project. So, I will again be pushing code updates and helping with user support.

Please let me know if you still need help with this specific issue and even if not, I would still like to get your feedback anyway:

https://wordpress.org/support/topic/important-announcement-3/

Thanks!
