### ISSUE TITLE
Next/Previous Page not displaying

### ISSUE THREAD

**Issue by bknightvpppa** [tidythemes/blankslate#30]
I need help with WordPress' native Next/Previous option that should appear on pages that display # of posts.  The BlankSlate theme is what's being used on my beta site and, unfortunately, Next/Previous are not displaying.  I have my Reading settings dialed to display 3 posts per page - I'm using a small number just for testing purposes.  I thought the pagination would automatically display but it hasn’t. I’m not using custom code or plugins, just the basic Posts and Latest Posts Widget that come with WordPress.  My beta site is beta.vpppa.org and this is for the News and Blog sections, both of which have 10 or more posts associated with each category.

**Comment by ve3** [comment]
It's displaying on my testing site.

For home page -> it's displaying 
> **← older newer →** 
at the bottom.

For category, tag page -> it's displaying the same as home page.
For author, search, archive page -> the same as above.

For single post -> it's displaying paginated on the contents that use `<!--nextpage-->` tag as 
> **Pages: 1 2 3**

And for next or previous post in single post page -> it's displaying this for example.
>← Block category: Embeds
Block: Quote →

They are work as expect but no style, so it is hard to find but it work. 😉

**Comment by bhadaway** [comment]
Thank you @ve3, that is very helpful.

What that means @bknightvpppa, is that it's not actually an issue that's present within the theme, but rather an isolated issue on your site.

If you can give me the link to where the issue is and more details (for instance, have you customized BlankSlate's default code in any way?) I can try and help you troubleshoot.
