### ISSUE TITLE
Featured Image alt and title attributes

### ISSUE THREAD

**Issue by robertandrews** [tidythemes/blankslate#42]
I was looking at attributes pumped out in entry-content.php for Featured Image (thumbnail).

https://github.com/tidythemes/blankslate/blob/2d962efd60eca295ded848297fb7843b660bc0bf/entry-content.php#L3

I think I see two things...

1. For `title` of the image page permalink, you use the value for the _post_ title (`the_title_attribute()`) >>> I'm curious - why not the Title of the _media asset_ that is being linked to?
2. ~~You then show the Featured Image with `the_post_thumbnail`, only passing `itemprop` of `image` >>> I believe it [supports](https://wordpress.stackexchange.com/a/120530/39300) showing the Alt text and Title text of the image at this point, which would [enhance accessibility and search](https://www.wpromote.com/blog/seo/image-alt-vs-title-using-alt-title-attributes-in-image-tags).~~

Not sure if this is also the case for in-post or other images.

And "d'oh" if I've got the wrong end of the stick.

**Comment by bhadaway** [comment]
1. I'm not 100% sure it's still the standard, but using `the_title_attribute` instead of just the `the_title` is simply an escaping shortcut (see: https://pippinsplugins.com/use-the_title-and-the_title_attribute-correctly/). So, rather than using `esc_attr( the_title() )`, we can just use `the_title_attribute`. That said, I'm sure this needs improvement throughout the theme concerning consistency.
2. The missing alt is simply an oversight, that I need to fix.

**Comment by bhadaway** [comment]
Never mind on the alt; it's already being adding in automatically.

Concerning the title though, it's showing the title of the post, but not the image itself, which is not right. I'm trying to fix that now...

**Comment by robertandrews** [comment]
> Never mind on the alt; it's already being adding in automatically.

Silly me. I was using an example of an image which didn't have `alt` set. WordPress figures it out by itself.

**Comment by bhadaway** [comment]
Finally got the title tag sorted. It'll be in the next update. Thanks.
