### ISSUE TITLE
Website Breaking On PHP 8.2 and then on 7.4 when updating theme

### ISSUE THREAD

**Issue by roosites** [tidythemes/blankslate#55]
Hello

I am taking over a website using BlankSlate. I migrated the site over and it had a fatal error as my server is on PHP 8.2.  I reverted back to 7.4 and it loaded fine. BUT then I tried to update the theme to the latest version and it breaks the site.

Can someone help me with it, glad to pay for your time.
My staging url is: https://alluredays1stg.wpenginepowered.com/

Thanks

**Comment by bhadaway** [comment]
1. What's the specific fatal error message?
2. Is a child theme being used? If not, updating the theme would completely overwrite any customizations made. If a child theme isn't being used, I would recommend either changing the version number of your theme to 9999 or give it a unique name so that it no longer prompts for an update.

**Comment by roosites** [comment]
Thanks for responding. I enclose the error messages. I get a ton of errors as soon as I update to php 8.2.  As I have just taken over the site, I don't really have any historical knowledge, and it looks like a lot of things are breaking. Everything looks fine in 7.4.  They did not use a child theme when they built this.  

￼

**Comment by bhadaway** [comment]
Doesn't look like you shared any errors. You can use a paste bin like https://privatebin.io/ to share them.

In any case, it doesn't sound like these errors are necessarily related to BlankSlate, but rather the entire WordPress installation as a whole. You could try PHP 8.1 instead of 8.2, but definitely don't upgrade to PHP 8.3 yet (see: https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/).

Since they didn't use a child theme or give the theme its own unique name, it's not safe to update BlankSlate.

It sounds like you're going to need more help than just basic user support, which if that's the case, feel free to email me: bhadaway@gmail.com.
